version: '3'
services:
  movies:
    image: raziasultana/moviesservice:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: raziasultana/trainservice:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: raziasultana/dthservice:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: raziasultana/rechargeservice:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
